# Generated by Django 5.2.8 on 2026-04-11 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="employer_organization_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this employer account shares the primary owner's jobs and company profile.",
                limit_choices_to={"role": "employer"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employer_team_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
