# Generated by Django 5.2.8 on 2026-06-02 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_employer_team_invites"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plan_type", models.CharField(choices=[("free", "Free"), ("premium", "Premium")], default="free", max_length=16)),
                ("status", models.CharField(choices=[("active", "Active"), ("cancelled", "Cancelled")], default="active", max_length=16)),
                ("monthly_price", models.DecimalField(decimal_places=2, default=5.99, max_digits=6)),
                ("member_since", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "candidate"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
