# Generated by Django 5.2.8 on 2026-04-07 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("contact", models.CharField(blank=True, max_length=255)),
                ("education_level", models.CharField(blank=True, max_length=120)),
                ("major", models.CharField(blank=True, max_length=120)),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("preferred_mode", models.CharField(blank=True, max_length=20)),
                ("summary", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/")),
                ("raw_text", models.TextField(blank=True)),
                ("parsed_json", models.JSONField(blank=True, default=dict)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
        ),
    ]
