# Generated by Django 5.2.8 on 2026-04-09 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
        ("employers", "0002_candidate_onboarding_and_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="onboarding_step",
            field=models.CharField(
                choices=[
                    ("signup", "Account created"),
                    ("resume", "Resume and experience"),
                    ("categories", "Job category preferences"),
                    ("done", "Onboarding complete"),
                ],
                default="resume",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="postcode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="preferred_job_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="preferred_by_candidates",
                to="employers.jobcategory",
            ),
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-start_date", "id"],
            },
        ),
    ]
