# Generated by Django 5.2.8 on 2026-04-11 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_candidate_onboarding_and_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=255)),
                ("degree", models.CharField(blank=True, max_length=255)),
                ("field_of_study", models.CharField(blank=True, max_length=255)),
                ("major", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_entries",
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-start_date", "id"],
            },
        ),
    ]
