# Generated by Django 5.2.8 on 2026-06-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0004_profile_dashboard_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateSavedSearch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={"ordering": ["-updated_at", "-created_at"]},
        ),
    ]
