# Generated by Django 5.2.8 on 2026-04-11 10:11

from django.db import migrations, models


def forwards_draft_to_open(apps, schema_editor):
    JobPosting = apps.get_model("employers", "JobPosting")
    JobPosting.objects.filter(status="draft").update(status="open")


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0008_jobposting_licenses_compensation"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="closing_date",
            field=models.DateField(
                blank=True,
                help_text="Last day the job is advertised publicly; after this date it is hidden unless status is reopened.",
                null=True,
            ),
        ),
        migrations.RunPython(forwards_draft_to_open, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1–10 employees"),
                    ("11-50", "11–50 employees"),
                    ("51-200", "51–200 employees"),
                    ("201-500", "201–500 employees"),
                    ("501-1000", "501–1,000 employees"),
                    ("1000+", "1,000+ employees"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Short public location line (e.g. shown on job listings).",
                max_length=255,
            ),
        ),
    ]
