# Generated by Django 5.2.8 on 2026-04-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0009_job_closing_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="jd_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
