# Generated by Django 5.2.8 on 2026-04-11 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0013_job_why_choose_us_bullets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerTeamInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Invitee must register with this exact email.",
                        max_length=254,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_team_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization_owner",
                    models.ForeignKey(
                        help_text="Canonical employer user (workspace root) whose jobs and company profile are shared.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_team_invites_for_org",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization_owner", "email"],
                        name="employers_e_organiz_974504_idx",
                    ),
                    models.Index(fields=["token"], name="employers_e_token_8b9597_idx"),
                ],
            },
        ),
    ]
