# Generated by Django 6.0.4 on 2026-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0014_employer_team_invites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='looking_for_additional_bullets',
            field=models.JSONField(blank=True, default=list, help_text='Bullets after "In addition, you will need:" (licences, experience, etc.).'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='looking_for_people_bullets',
            field=models.JSONField(blank=True, default=list, help_text='Bullets after "We are looking for people who:".'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='role_bullets',
            field=models.JSONField(blank=True, default=list, help_text='Bullets after "In this role you will be providing, such as:".'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='whats_on_offer',
            field=models.JSONField(blank=True, default=list, help_text='Bullet list of benefits, perks, and what the hire gains (stored as JSON array of strings).'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='why_choose_us_bullets',
            field=models.JSONField(blank=True, default=list, help_text='Bullets after the fixed "Why choose us" line (culture, mission, accreditation, growth).'),
        ),
    ]
