# Generated by Django 5.2.8 on 2026-04-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        ("candidates", "0004_profile_dashboard_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="cover_letter_file",
            field=models.FileField(blank=True, upload_to="cover_letters/"),
        ),
        migrations.AddField(
            model_name="application",
            name="cover_letter_mode",
            field=models.CharField(
                choices=[
                    ("none", "No cover letter"),
                    ("in_app", "Written on SkillMesh"),
                    ("upload", "Uploaded file"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="cover_letter_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="candidates.resumedocument",
            ),
        ),
    ]
