"""Region lists for employer address autocomplete (states/provinces by ISO country code)."""

# Full names; matches common Nominatim / postcode API spellings where possible.

COUNTRIES = [
    {"name": "Australia", "code": "AU"},
    {"name": "Austria", "code": "AT"},
    {"name": "Belgium", "code": "BE"},
    {"name": "Brazil", "code": "BR"},
    {"name": "Canada", "code": "CA"},
    {"name": "China", "code": "CN"},
    {"name": "Denmark", "code": "DK"},
    {"name": "Egypt", "code": "EG"},
    {"name": "Finland", "code": "FI"},
    {"name": "France", "code": "FR"},
    {"name": "Germany", "code": "DE"},
    {"name": "Greece", "code": "GR"},
    {"name": "Hong Kong", "code": "HK"},
    {"name": "India", "code": "IN"},
    {"name": "Indonesia", "code": "ID"},
    {"name": "Ireland", "code": "IE"},
    {"name": "Israel", "code": "IL"},
    {"name": "Italy", "code": "IT"},
    {"name": "Japan", "code": "JP"},
    {"name": "Malaysia", "code": "MY"},
    {"name": "Mexico", "code": "MX"},
    {"name": "Netherlands", "code": "NL"},
    {"name": "New Zealand", "code": "NZ"},
    {"name": "Norway", "code": "NO"},
    {"name": "Pakistan", "code": "PK"},
    {"name": "Philippines", "code": "PH"},
    {"name": "Poland", "code": "PL"},
    {"name": "Portugal", "code": "PT"},
    {"name": "Singapore", "code": "SG"},
    {"name": "South Africa", "code": "ZA"},
    {"name": "South Korea", "code": "KR"},
    {"name": "Spain", "code": "ES"},
    {"name": "Sweden", "code": "SE"},
    {"name": "Switzerland", "code": "CH"},
    {"name": "Taiwan", "code": "TW"},
    {"name": "Thailand", "code": "TH"},
    {"name": "Turkey", "code": "TR"},
    {"name": "United Arab Emirates", "code": "AE"},
    {"name": "United Kingdom", "code": "GB"},
    {"name": "United States", "code": "US"},
    {"name": "Vietnam", "code": "VN"},
    {"name": "Argentina", "code": "AR"},
    {"name": "Bangladesh", "code": "BD"},
    {"name": "Chile", "code": "CL"},
    {"name": "Colombia", "code": "CO"},
    {"name": "Czech Republic", "code": "CZ"},
    {"name": "Hungary", "code": "HU"},
    {"name": "Iceland", "code": "IS"},
    {"name": "Jordan", "code": "JO"},
    {"name": "Kenya", "code": "KE"},
    {"name": "Luxembourg", "code": "LU"},
    {"name": "Morocco", "code": "MA"},
    {"name": "Nepal", "code": "NP"},
    {"name": "Nigeria", "code": "NG"},
    {"name": "Peru", "code": "PE"},
    {"name": "Romania", "code": "RO"},
    {"name": "Saudi Arabia", "code": "SA"},
    {"name": "Slovakia", "code": "SK"},
    {"name": "Slovenia", "code": "SI"},
    {"name": "Sri Lanka", "code": "LK"},
    {"name": "Ukraine", "code": "UA"},
    {"name": "Uruguay", "code": "UY"},
]

AU_SUBURB_POSTCODES = [
    {"suburb": "Sydney", "postcode": "2000", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Sydney Olympic Park", "postcode": "2127", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Parramatta", "postcode": "2150", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Liverpool", "postcode": "2170", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Blacktown", "postcode": "2148", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Penrith", "postcode": "2750", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Wollongong", "postcode": "2500", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Newcastle", "postcode": "2300", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Campbelltown", "postcode": "2560", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Bondi", "postcode": "2026", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Melbourne", "postcode": "3000", "state": "Victoria", "country_code": "AU"},
    {"suburb": "Southbank", "postcode": "3006", "state": "Victoria", "country_code": "AU"},
    {"suburb": "Docklands", "postcode": "3008", "state": "Victoria", "country_code": "AU"},
    {"suburb": "Geelong", "postcode": "3220", "state": "Victoria", "country_code": "AU"},
    {"suburb": "Ballarat", "postcode": "3350", "state": "Victoria", "country_code": "AU"},
    {"suburb": "Bendigo", "postcode": "3550", "state": "Victoria", "country_code": "AU"},
    {"suburb": "Brisbane", "postcode": "4000", "state": "Queensland", "country_code": "AU"},
    {"suburb": "South Brisbane", "postcode": "4101", "state": "Queensland", "country_code": "AU"},
    {"suburb": "Fortitude Valley", "postcode": "4006", "state": "Queensland", "country_code": "AU"},
    {"suburb": "Gold Coast", "postcode": "4217", "state": "Queensland", "country_code": "AU"},
    {"suburb": "Sunshine Coast", "postcode": "4558", "state": "Queensland", "country_code": "AU"},
    {"suburb": "Cairns", "postcode": "4870", "state": "Queensland", "country_code": "AU"},
    {"suburb": "Adelaide", "postcode": "5000", "state": "South Australia", "country_code": "AU"},
    {"suburb": "Norwood", "postcode": "5067", "state": "South Australia", "country_code": "AU"},
    {"suburb": "Perth", "postcode": "6000", "state": "Western Australia", "country_code": "AU"},
    {"suburb": "Fremantle", "postcode": "6160", "state": "Western Australia", "country_code": "AU"},
    {"suburb": "Bunbury", "postcode": "6230", "state": "Western Australia", "country_code": "AU"},
    {"suburb": "Hobart", "postcode": "7000", "state": "Tasmania", "country_code": "AU"},
    {"suburb": "Launceston", "postcode": "7250", "state": "Tasmania", "country_code": "AU"},
    {"suburb": "Canberra", "postcode": "2600", "state": "Australian Capital Territory", "country_code": "AU"},
    {"suburb": "Belconnen", "postcode": "2617", "state": "Australian Capital Territory", "country_code": "AU"},
    {"suburb": "Darwin", "postcode": "0800", "state": "Northern Territory", "country_code": "AU"},
    {"suburb": "Palmerston", "postcode": "0830", "state": "Northern Territory", "country_code": "AU"},
    {"suburb": "Auburn", "postcode": "2144", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Rockdale", "postcode": "2216", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Bankstown", "postcode": "2200", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Chatswood", "postcode": "2067", "state": "New South Wales", "country_code": "AU"},
    {"suburb": "Hurstville", "postcode": "2220", "state": "New South Wales", "country_code": "AU"},
]

AU_STATES = [
    "Australian Capital Territory",
    "New South Wales",
    "Northern Territory",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia",
]

NZ_REGIONS = [
    "Auckland",
    "Bay of Plenty",
    "Canterbury",
    "Gisborne",
    "Hawke's Bay",
    "Manawatū-Whanganui",
    "Marlborough",
    "Nelson",
    "Northland",
    "Otago",
    "Southland",
    "Taranaki",
    "Tasman",
    "Waikato",
    "Wellington",
    "West Coast",
]

CA_PROVINCES = [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon",
]

GB_NATIONS = [
    "England",
    "Northern Ireland",
    "Scotland",
    "Wales",
]

DE_STATES = [
    "Baden-Württemberg",
    "Bavaria",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse",
    "Lower Saxony",
    "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia",
    "Rhineland-Palatinate",
    "Saarland",
    "Saxony",
    "Saxony-Anhalt",
    "Schleswig-Holstein",
    "Thuringia",
]

FR_REGIONS = [
    "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté",
    "Brittany",
    "Centre-Val de Loire",
    "Corsica",
    "Grand Est",
    "Hauts-de-France",
    "Île-de-France",
    "Normandy",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Pays de la Loire",
    "Provence-Alpes-Côte d'Azur",
]

IN_STATES = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
]

# US — 50 states + DC
_US = (
    "Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,"
    "Florida,Georgia,Hawaii,Idaho,Illinois,Indiana,Iowa,Kansas,Kentucky,Louisiana,Maine,Maryland,"
    "Massachusetts,Michigan,Minnesota,Mississippi,Missouri,Montana,Nebraska,Nevada,New Hampshire,"
    "New Jersey,New Mexico,New York,North Carolina,North Dakota,Ohio,Oklahoma,Oregon,Pennsylvania,"
    "Rhode Island,South Carolina,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,"
    "West Virginia,Wisconsin,Wyoming"
)
US_STATES = [s.strip() for s in _US.split(",")]

STATES_BY_COUNTRY = {
    "AU": AU_STATES,
    "NZ": NZ_REGIONS,
    "CA": CA_PROVINCES,
    "GB": GB_NATIONS,
    "DE": DE_STATES,
    "FR": FR_REGIONS,
    "IN": IN_STATES,
    "US": US_STATES,
}
